import('@/mocks').then(({ setupMocks }) => setupMocks());

import React from 'react';

import { Roboto } from 'next/font/google';

import { StyledComponentsRegistry } from '@/lib/regitry';
import { GlobalStyles } from '@/styles/global';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <main id="root">
            {children}

            <GlobalStyles />
          </main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
